import { useCallback, useState } from "react";
import type { NextPage } from "next";
import { Map, Marker } from "pigeon-maps";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [position, setPosition] = useState<[number, number]>([50.879, 4.6997]);

  const handleClickMap = useCallback(
    ({ latLng }: { latLng: [number, number] }) => {
      setPosition(latLng);
    },
    [setPosition]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Map
          height={600}
          defaultCenter={position}
          defaultZoom={4}
          onClick={handleClickMap}
        >
          <Marker width={50} anchor={position} />
        </Map>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
